<?php
include "config.php";

// Global scope
// Constants
define( "IMAGE", "germany.png" );
define( "IMAGE_WIDTH", "856" );
define( "IMAGE_HEIGHT", "777" );
define( "UPPER_LEFT_X", 3.78 );
define( "UPPER_LEFT_Y", 55.90 );
define( "MULTIPLIER_X", 55.06329114 );
define( "MULTIPLIER_Y", -71.66666666 );
define( "RADIUS", 4 );
define( "NORTH_DIVERGENCE", 0.1 );
define( "EAST_DIVERGENCE", 0.1 );
define( "VERSION", "0.99-r3" );
?>
